/**
 * Base class for embedding providers
 * This serves as an interface that all embedding providers should implement
 */
class EmbeddingProviderBase {
  /**
   * Generate an embedding for the given text
   * @param {string} text - The text to generate an embedding for
   * @returns {Promise<number[]>} - A promise that resolves to an array of numbers representing the embedding
   */
  async embed(text) {
    throw new Error('Method embed() must be implemented by subclass');
  }

  /**
   * Get the dimension of the embeddings generated by this provider
   * @returns {number} - The dimension of the embeddings
   */
  getDimension() {
    throw new Error('Method getDimension() must be implemented by subclass');
  }
}

module.exports = EmbeddingProviderBase;
